export const SET_POSITION_DATA = 'SET_POSITION_DATA';

export const GET_INSTRUMENT_SUCCESS = 'GET_INSTRUMENT_SUCCESS';
export const GET_INSTRUMENT_FAIL = 'GET_INSTRUMENT_FAIL';
export const ATTEMPT_GET_INSTRUMENT = 'ATTEMPT_GET_INSTRUMENT';

export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const ATTEMPT_GET_TRANSACTIONS = 'ATTEMPT_GET_TRANSACTIONS';

export const SET_TOGGLE_MENU = 'SET_TOGGLE_MENU';
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';

export const SET_CONTEXTMENUDATA_LOAD_STATUS = 'SET_CONTEXTMENUDATA_LOAD_STATUS';
