export const POSITION_TOGGLE_DRAWER = 'POSITION_TOGGLE_DRAWER';
export const POSITION_DRAWER_EXPAND = 'POSITION_DRAWER_EXPAND';
export const TRANSACTION_TOGGLE_DRAWER = 'TRANSACTION_TOGGLE_DRAWER';
export const TOGGLE_ASSET_DETAIL_DRAWER = 'TOGGLE_ASSET_DETAIL_DRAWER';
export const TOGGLE_ADD_VALUATION_DRAWER = 'TOGGLE_ADD_VALUATION_DRAWER';
