export enum TransactionTypes {
  BUY = 'Buy',
  CREDIT = 'Credit',
  DEPOSIT = 'Deposit',
  DISTRIBUTION = 'Distribution',
  MATURITY = 'Maturity',
  RECEIVE = 'Receive',
  SECURITYTRANSFERIN = 'SecurityTransferIn',
  COMMIT = 'Commit',
  INVESTMENT = 'Investment',
  CONTRIBUTE = 'Contribute',
  DEBIT = 'Debit',
  EXPENSE = 'Expense',
  INTERESTPAYMENT = 'InterestPayment',
  INTERESTRUN = 'InterestRun',
  PARTIALREDEMPTION = 'PartialRedemption',
  SECURITYTRANSFEROUT = 'SecurityTransferOut',
  SELL = 'Sell',
  WITHDRAWAL = 'Withdrawal',
}
