export const ATTEMPT_GET_PORTFOLIO_TABLE = 'ATTEMPT_GET_PORTFOLIO_TABLE';
export const GET_PORTFOLIO_TABLE_SUCCESS = 'GET_PORTFOLIO_TABLE_SUCCESS';
export const GET_PORTFOLIO_TABLE_FAIL = 'GET_PORTFOLIO_TABLE_FAIL';

export const ATTEMPT_GET_PORTFOLIOS = 'ATTEMPT_GET_PORTFOLIOS';
export const GET_PORTFOLIOS_SUCCESS = 'GET_PORTFOLIOS_SUCCESS';
export const GET_PORTFOLIOS_FAIL = 'GET_PORTFOLIOS_FAIL';

export const SET_SELECTED_PORTFOLIO = 'SET_SELECTED_PORTFOLIO';

export const ATTEMPT_GET_PERFORMERS = 'ATTEMPT_GET_PERFORMERS';
export const GET_PERFORMERS_SUCCESS = 'GET_PERFORMERS_SUCCESS';
export const GET_PERFORMERS_FAIL = 'GET_PERFORMERS_FAIL';

export const ATTEMPT_GET_MATURITIES = 'ATTEMPT_GET_MATURITIES';
export const GET_MATURITIES_SUCCESS = 'GET_MATURITIES_SUCCESS';
export const GET_MATURITIES_FAIL = 'GET_MATURITIES_FAIL';

export const ATTEMPT_GET_ALLOCATIONS = 'ATTEMPT_GET_ALLOCATIONS';
export const GET_ALLOCATIONS_SUCCESS = 'GET_ALLOCATIONS_SUCCESS';
export const GET_ALLOCATIONS_FAIL = 'GET_ALLOCATIONS_FAIL';

export const ATTEMPT_GET_DAILY_PERFORMANCE = 'ATTEMPT_GET_DAILY_PERFORMANCE';
export const GET_DAILY_PERFORMANCE_SUCCESS = 'GET_DAILY_PERFORMANCE_SUCCESS';
export const GET_DAILY_PERFORMANCE_FAIL = 'GET_DAILY_PERFORMANCE_FAIL';

export const ATTEMPT_GET_PORTFOLIO_TRANSACTIONS = 'ATTEMPT_GET_PORTFOLIO_TRANSACTIONS';
export const GET_PORTFOLIO_TRANSACTIONS_SUCCESS = 'GET_PORTFOLIO_TRANSACTIONS_SUCCESS';
export const GET_PORTFOLIO_TRANSACTIONS_FAIL = 'GET_PORTFOLIO_TRANSACTIONS_FAIL';

export const SET_PORTFOLIO_ID = 'SET_PORTFOLIO_ID';

export const VALIDATE_COMPONENT_DASHBOARD_MOUNT = 'VALIDATE_COMPONENT_DASHBOARD_MOUNT';
export const VALIDATE_COMPONENT_PA_MOUNT = 'VALIDATE_COMPONENT_PA_MOUNT';
export const VALIDATE_COMPONENT_TRANSACTION_MOUNT = 'VALIDATE_COMPONENT_TRANSACTION_MOUNT';
